# Generated by Django 2.1.7 on 2019-03-14 16:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('model_example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=13)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('synopsis', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Example',
        ),
    ]
