version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:11.2-alpine
    restart: always
    # if you're going to use this 
    # it's better to use a file outside the repo
    # read: https://docs.docker.com/compose/environment-variables/  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: modelviewsetexample
    ports:
      - "5432"
    # data persistance in local mounting, because docker data is ephemeral
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - mynetwork
  pythonexample:
    container_name: pythonexample
    build:
      context: .
      dockerfile: Dockerfile
    # restart: always
    # python unbuffered fixed lagging output to the console
    environment:
      - "PYTHONUNBUFFERED=1"
    working_dir: /usr/src/modelviewsetexample
    depends_on:
      - "postgres"
    ports:
      - "8000:8000"
    volumes:
      - /DRF_ModelViewSet_Responsive_Example:/usr/src/modelviewsetexample
    networks:
      - mynetwork
    command: >
      sh -c "./wait.sh postgres:5432 -- python manage.py runserver 0.0.0.0:8000"
volumes:
  postgres_data:
networks:
  mynetwork:
