# Generated by Django 2.1.7 on 2019-03-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_example', '0002_auto_20190314_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
